[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#6366f1"
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"
